services:
# docker-compose.yml
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:8088"
    ports:
      - "8088:8088"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  frontend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.dev-frontend
    develop:
      watch:
        - action: sync
          path: ../frontend/super-eureka
          target: /frontend
          initial_sync: true
          ignore:
            - node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`eureka.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  backend:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.dev-go
    environment:
      - BASE_URL=/dev
    develop:
      watch:
        - action: rebuild
          path: ../internal
          ignore: 
            - frontend
            - docker
            - database
          
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`eureka.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
  db:
    image: postgres:18
    volumes:
      - ../database:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/18/docker
    env_file:
      - ../.env
  keycloak:
    image:  quay.io/keycloak/keycloak:26.4.7
    env_file:
      - ../.env
    ports:
      - "8090:8080"
    command: start-dev
volumes:
  data:

  